---
- name: Ensure Mozilla Opt directory
  file:
    name: "{{ mozilla_firefox_dest }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true
  tags:
    - mozilla-firefox

- name: Ensure latest Mozilla Firefox in Opt
  unarchive:
    src: https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US
    remote_src: true
    dest: "{{ mozilla_firefox_dest }}"
    creates: "{{ mozilla_firefox_dest }}/firefox"
  become: true
  tags:
    - mozilla-firefox

- name: Ensure user permissions for Firefox Opt directory
  file:
    name: "{{ mozilla_firefox_dest }}/firefox"
    state: directory
    owner: "{{ mozilla_firefox_user }}"
    group: "{{ mozilla_firefox_group }}"
    mode: '0775'
  become: true
  tags:
    - mozilla-firefox

- name: Ensure user permissions for Firefox Opt files
  file:
    name: "{{ mozilla_firefox_dest }}/firefox"
    recurse: true
    state: directory
    owner: "{{ mozilla_firefox_user }}"
    group: "{{ mozilla_firefox_group }}"
    mode: g+w
  become: true
  tags:
    - mozilla-firefox

- name: Ensure local applications directory
  file:
    name: /usr/local/share/applications
    state: directory
    owner: "{{ mozilla_firefox_user }}"
    group: "{{ mozilla_firefox_group }}"
    mode: '0775'
  become: true
  tags:
    - mozilla-firefox

- name: Ensure Firefox Opt desktop file
  template:
    src: firefox-opt.desktop.j2
    dest: /usr/local/share/applications/firefox-opt.desktop
    owner: "{{ mozilla_firefox_user }}"
    group: "{{ mozilla_firefox_group }}"
    mode: '0664'
  become: true
  tags:
    - mozilla-firefox
